/* fizmo_compat.c - Compatibility stubs for building fizmo with WASI.
 *
 * Provides:
 * - Hyphenation pattern stubs (normally generated by pattern_setup tool)
 * - Locale stubs for libfizmo (normally generated by locale_setup tool)
 *   Note: libglkif locale data is real and compiled from libglkif/src/locales/
 */

#include <stddef.h>
#include <stdint.h>

#include <tools/types.h>
#include <tools/i18n.h>

/* Stub for hyph_patterns - normally generated by pattern_setup tool */
#define hyph_patterns_c_INCLUDED

stringmap *pattern_map = NULL;

void init_patterns(void) {
  /* No hyphenation patterns compiled in */
}

int cmp_pattern(z_ucs *s1, z_ucs *s2) {
  while (*s1 && *s1 == *s2) { s1++; s2++; }
  return *s1 - *s2;
}

/* Locale stubs for libfizmo only - normally generated by locale_setup tool.
 * libglkif has real locale data in its own locale_data.c */
locale_module locale_module_libfizmo = { NULL, NULL };

void init_libfizmo_locales(void) {
  /* No locale data compiled in */
}
