/* fizmo_compat.h - Force-included header for WASI compatibility.
 *
 * Provides forward declarations for symbols normally generated by
 * fizmo's locale_setup tool. This header is force-included (-include)
 * so it runs before any fizmo source. Since it includes <tools/i18n.h>
 * (which has include guards), the real locale_module type is available.
 */

#ifndef FIZMO_COMPAT_H
#define FIZMO_COMPAT_H

#include <tools/i18n.h>

/* libfizmo locale stubs (normally generated by locale_setup tool).
 * libglkif locales are real and come from libglkif/src/locales/locale_data.c */
extern locale_module locale_module_libfizmo;
void init_libfizmo_locales(void);

#endif /* FIZMO_COMPAT_H */
